config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'users'
  devise_for :admins, path: 'admins'
  root 'scraper#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :fields
  resources :scrape_methods

  get '/scrape_methods/new_using_meta_tag' => 'scrape_methods#new_using_meta_tag'
end

app/models/scrape_method.rb
class ScrapeMethod < ActiveRecord::Base
  belongs_to :field
end

app/controllers/scrape_methods_controller.rb
class ScrapeMethodsController < ApplicationController
  before_action :set_scrape_method, only: [:show, :edit, :update, :destroy]
  before_action :set_fields, only: [:new, :edit]
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  # GET /scrape_methods
  # GET /scrape_methods.json
  def index
    @scrape_methods = ScrapeMethod.all
  end

  # GET /scrape_methods/1
  # GET /scrape_methods/1.json
  def show
    
  end

  # GET /scrape_methods/new
  def new
    @scrape_method = ScrapeMethod.new
  end

  # GET /scrape_methods/new_using_meta_tag
  # def new_using_meta_tag

  # end

  # GET /scrape_methods/1/edit
  def edit
  end

  # POST /scrape_methods
  # POST /scrape_methods.json
  def create
    @scrape_method = ScrapeMethod.new(scrape_method_params)

    respond_to do |format|
      if @scrape_method.save
        format.html { redirect_to @scrape_method, notice: 'Scrape method was successfully created.' }
        format.json { render :show, status: :created, location: @scrape_method }
      else
        format.html { render :new }
        format.json { render json: @scrape_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scrape_methods/1
  # PATCH/PUT /scrape_methods/1.json
  def update
    respond_to do |format|
      if @scrape_method.update(scrape_method_params)
        format.html { redirect_to @scrape_method, notice: 'Scrape method was successfully updated.' }
        format.json { render :show, status: :ok, location: @scrape_method }
      else
        format.html { render :edit }
        format.json { render json: @scrape_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scrape_methods/1
  # DELETE /scrape_methods/1.json
  def destroy
    @scrape_method.destroy
    respond_to do |format|
      format.html { redirect_to scrape_methods_url, notice: 'Scrape method was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scrape_method
      @scrape_method = ScrapeMethod.find(params[:id])
    end

    def set_fields
      @fields = Field.all.pluck(:name, :id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scrape_method_params
      params.require(:scrape_method).permit(:method, :field_id)
    end

end

app/helpers/scrape_methods_helper.rb
module ScrapeMethodsHelper
  def new_scrape_method_using_meta_tags_path
    '/scrape_methods/new_using_meta_tag'
  end
end

app/views/scrape_methods/_form.html.erb
<%= form_for(scrape_method, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if scrape_method.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(scrape_method.errors.count, "error") %> prohibited this scrape method from being saved:</h4>

      <ul>
      <% scrape_method.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :method, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :method, class: "form-control", required: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :field_id, class:'col-lg-2 control-label'  %>
    <div class="col-lg-10">
      <%= f.select :field_id, @fields, {}, { class: "form-control", required: true } %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/scrape_methods/edit.html.erb
<div class="page-header">
  <%= link_to scrape_methods_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @scrape_method, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing Scrape Method</h1>
</div>

<%= render 'form', scrape_method: @scrape_method %>

app/views/scrape_methods/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <%= link_to new_scrape_method_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Scrape Method
  <% end %>
  <h1>Scrape Methods</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Method</th>
        <th>Field</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @scrape_methods) do |scrape_method| %>
          <td><%= scrape_method.method %></td>
          <td><%= scrape_method.field.name %></td>
          <td><%= link_to 'Show', scrape_method %></td>
          <td><%= link_to 'Edit', edit_scrape_method_path(scrape_method) %></td>
          <td><%= link_to 'Destroy', scrape_method, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/scrape_methods/new.html.erb
<div class="page-header">
  <%= link_to scrape_methods_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Scrape Method</h1>
</div>

<%= render 'form', scrape_method: @scrape_method %>

app/views/scrape_methods/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <%= link_to scrape_methods_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_scrape_method_path(@scrape_method), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show Method</h1>
</div>

<p>
  <strong>Method:</strong>
  <%= @scrape_method.method %>
</p>

<p>
  <strong>Field:</strong>
  <%= @scrape_method.field.name %>
</p>