config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'users'
  devise_for :admins, path: 'admins'
  root 'scraper#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :fields
  resources :scrape_methods

  get '/scrape_methods/new_using_meta_tag' => 'scrape_methods#new_using_meta_tag'
end

app/models/field.rb
class Field < ActiveRecord::Base
  belongs_to :schema, optional: true

  has_many :scrape_methods
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: [:show, :edit, :update, :destroy]
  before_action :set_schemas, only: [:new, :edit]
  before_action :authenticate_user!, only: [:new, :edit, :destroy]

  # GET /fields
  # GET /fields.json
  def index
    @fields = Field.all
  end

  # GET /fields/1
  # GET /fields/1.json
  def show
  end

  # GET /fields/new
  def new
    @field = Field.new
  end

  # GET /fields/1/edit
  def edit
  end

  # POST /fields
  # POST /fields.json
  def create
    @field = Field.new(field_params)

    respond_to do |format|
      if @field.save
        format.html { redirect_to @field, notice: 'Field was successfully created.' }
        format.json { render :show, status: :created, location: @field }
      else
        format.html { render :new }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fields/1
  # PATCH/PUT /fields/1.json
  def update
    respond_to do |format|
      if @field.update(field_params)
        format.html { redirect_to @field, notice: 'Field was successfully updated.' }
        format.json { render :show, status: :ok, location: @field }
      else
        format.html { render :edit }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.json
  def destroy
    @field.destroy
    respond_to do |format|
      format.html { redirect_to fields_url, notice: 'Field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
    end

    def set_schemas
      @schemas = Schema.all.pluck(:name, :id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_params
      params.require(:field).permit(:name, :schema_id)
    end
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_form.html.erb
<%= form_for(field, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if field.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(field.errors.count, "error") %> prohibited this scrape method from being saved:</h4>

      <ul>
      <% field.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class:'col-lg-2 control-label'  %>
    <div class="col-lg-10">
     <%= f.text_field :name, class: "form-control", required: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :schema_id, class:'col-lg-2 control-label'  %>
    <div class="col-lg-10">
      <%= f.select :schema_id, @schemas, {}, { class: "form-control", required: true } %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/fields/edit.html.erb
<!-- <h1>Editing Field</h1>

<%= render 'form', field: @field %>

<%= link_to 'Show', @field %> |
<%= link_to 'Back', fields_path %> -->

<div class="page-header">
  <%= link_to fields_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @field, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing Field</h1>
</div>

<%= render 'form', field: @field %>

app/views/fields/index.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  
    <%= link_to new_field_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Field
  <% end %>
  <h1>Field</h1>
</div>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Field</th>
        <th>Schema</th>
        <th>Scrape Methods</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <%= content_tag_for(:tr, @fields) do |field| %>
          <td><%= field.name %></td>
          <td><%= field.schema ? field.schema.name : '' %></td>
          <td><%= field.scrape_methods.collect(&:method).join(' | ') %></td>
          <td><%= link_to 'Show', field %></td>
          <td><%= link_to 'Edit', edit_field_path(field) %></td>
          <td><%= link_to 'Destroy', field, name: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/fields/new.html.erb
<!-- <h1>New Field</h1>

<%= render 'form', field: @field %>

<%= link_to 'Back', fields_path %> -->
<div class="page-header">
  <%= link_to fields_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Field</h1>
</div>

<%= render 'form', field: @field %>

app/views/fields/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <%= link_to fields_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_field_path(@field), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show Field</h1>
</div>
<p>
  <strong>Field:</strong>
  <%= @field.name %>
</p>